
###
POST http://localhost:8080/api/hospitals/1/patients
Content-Type: application/json

{
  "name": "Jane Doe",
  "registrationDate": "2022-05-16",
  "hospitalWard": "MEDICAL"
}


###
POST http://localhost:8080/api/hospitals
Content-Type: application/json

{
  "hospitalName": "Szent Benedek Kórház"
}

###
GET http://localhost:8080/api/hospitals/1/patients?hospitalWard=MEDICAL
Accept: application/json

###
GET http://localhost:8080/api/hospitals/1/patients?hospitalWard=ORTHOPAEDY
Accept: application/json

###
DELETE http://localhost:8080/api/hospitals/2/patients/2
Accept: application/json